### ISSUE TITLE
O que seria esse site?

### ISSUE THREAD

**Issue by eiguike** [UFSCar/website#1]
Seria uma substituição do http://www.dcomp.sor.ufscar.br/pedagogico/ ?

**Comment by mccraveiro** [comment]
Isso!

**Comment by eiguike** [comment]
+1, como posso ajudar? auhauauah o que você pretende modificar nele?

**Comment by mccraveiro** [comment]
Eu mudei apenas a interface para deixar mais bonita e fácil de usar. Porém a parte de administração por parte dos professores não está nem funcionando direto, precisa arrumar. Além disso tem umas funcionalidades a mais que a Tiemi quer como, por exemplo, uma página por disciplina que o professor possa editar. Tive algumas ideias mas não implementei nada. Também estou com as novas fotos dos professores aqui para atualizar :)

**Comment by eiguike** [comment]
Daora! Tem algum BD de exemplo para que eu possa utilizar aqui?

**Comment by mccraveiro** [comment]
@eiguike não temos não. Seria legal ter isso no projeto. De qualquer forma posso te enviar o banco que tenho aqui.
